# Build, test and deploy website via Travis

os: linux
dist: xenial
language: generic

branches:
  except:
    - gh-pages
    - /^untagged/

env:
  global:
    - HUGO_VERSION=0.75.1
    - HUGO_HASH=261fbc6b2bb835192761b9d9bf726c6dea89f8c71b15b6af63e3a8a574c8d4c5

before_install:
  # Set to fail on errors
  - set -o errexit && set -o pipefail
  # Install Hugo
  - .travis/install_hugo.sh
  # Install AWS CLI
  - .travis/install_awscli.sh
  # Export new tools to PATH
  - export PATH="${HOME}/.local/bin:${PATH}"
  # Reset shell
  - set +o errexit && set +o pipefail

jobs:
  include:
    # Build site to test it works
    - stage: Test
      script:
        - hugo -s site

    # Add archive of site to GitHub via releases
    - stage: Archive
      if: branch = master AND type != pull_request
      script:
        - hugo -s site
      before_deploy:
        - tar -czvf public.tar.gz site/public
      deploy:
        provider: releases
        api_key: "${GITHUB_TOKEN}"
        file: public.tar.gz
        skip_cleanup: true

    # Upload to S3 for public CDN
    - stage: Deploy
      if: branch = master AND type != pull_request
      script:
        - hugo -s site
      deploy:
        provider: script
        script:
          # Requires AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
          - aws s3 sync 'site/public' 's3://com.chelsislotten.www' --region='us-east-1' --acl='private' --delete
        skip_cleanup: true
      after_deploy:
        - aws cloudfront create-invalidation --distribution-id "${AWS_CLOUDFRONT_DISTRIBUTION_ID}" --paths '/*'

cache:
  directories:
    - ${HOME}/.local

